--1.각 직급별 가장많은 급여를 받는 교수의 이름 ,급여 출력(PROFESSOR)

SELECT * FROM PROFESSOR;

SELECT NAME , MAX_PAY
FROM PROFESSOR P1
INNER JOIN(
SELECT MAX(PAY) MAX_PAY , POSITION 
FROM PROFESSOR 
GROUP BY position )
T ON P1.POSITION = T.POSITION AND P1.PAY = T.MAX_PAY;



--2.본인 부서의 평균 급여보다 높은 급여를 받는 사원의 사번, 이름 , 급여 출력 (EMP)

SELECT  EMPNO, ENAME , SAL , AVG_SAL
FROM EMP E
INNER JOIN(
SELECT  DEPTNO , AVG(SAL) AVG_SAL
FROM EMP
GROUP BY DEPTNO
) T ON E.DEPTNO = T.DEPTNO  AND E.SAL > T.AVG_SAL;