
SELECT * FROM TBL_COMMENT;
SELECT * FROM TBL_USER;
SELECT * FROM TBL_BOARD;

SELECT NICKNAME , TITLE
FROM TBL_USER U
INNER JOIN TBL_BOARD C ON U.USERID = C.USERID;

SELECT NICKNAME, COUNT(*)
FROM TBL_BOARD B
INNER JOIN TBL_USER U ON  B.USERID =U.USERID
GROUP BY B.USERID,NICKNAME;

--각 게시글의 제목 , 댓글 개수 출력
SELECT COUNT(C.BOARDNO) ,B.TITLE
FROM TBL_BOARD B
LEFT JOIN TBL_COMMENT C ON B.BOARDNO = C.BOARDNO
GROUP BY B.BOARDNO , TITLE
;

SELECT *
FROM TBL_BOARD B
INNER JOIN TBL_COMMENT C ON B.BOARDNO = C.BOARDNO;
--GROUP BY B.BOARDNO , TITLE


--게시글 제목 , 내용 , 작성자 닉네임 , 댓글 개수(없으면 0),게시글번호,작성일

SELECT * FROM TBL_COMMENT;
SELECT * FROM TBL_USER;
SELECT * FROM TBL_BOARD;

SELECT COUNT(C.BOARDNO) ,B.TITLE , B.CONTENTS , NICKNAME,B.BOARDNO,B.CDATETIME
FROM TBL_BOARD B
LEFT JOIN TBL_COMMENT C ON B.BOARDNO = C.BOARDNO
LEFT JOIN TBL_USER U ON B.USERID = U.USERID
GROUP BY B.BOARDNO , TITLE , B.CONTENTS ,B.CDATETIME,NICKNAME;

--CASE -WHEN 
-- STU , PROFESSOR 
--1.PROFESSOR 테이블에서 400이상의 급여를 받으면 A,
-- 300~400사이면 B , 나머지는 C로 출력
-- 교수이름 , 급여 등습(A~C)
SELECT * FROM PROFESSOR;

SELECT CASE WHEN PAY >=400 THEN 'A'
WHEN PAY > 300  AND PAY <400 THEN'B'
ELSE 'C' END
FROM PROFESSOR;




