SELECT * FROM PROFESSOR;
SELECT * FROM DEPARTMENT;

SELECT P.DEPTNO , NAME, DNAME
FROM PROFESSOR  P
INNER JOIN DEPARTMENT D ON P.DEPTNO =D.DEPTNO;

SELECT * FROM EMP;
SELECT * FROM DEPT;

-- 사번, 이름 ,직급(JOB) ,부서명(DNAME),출력

SELECT E.DEPTNO , ENAME ,JOB , DNAME
FROM EMP E 
INNER JOIN DEPT D  ON  E.DEPTNO  = D.DEPTNO;

-- 학번 이름 학과 시험점수 출력
-- STUDENT ENROL
-- 과목명 SUBJECT

SELECT *FROM STUDENT;
SELECT *FROM ENROL;
SELECT *FROM SUBJECT;

SELECT S.STU_NO ,STU_NAME, STU_DEPT , ENR_GRADE , SUB_NAME 
FROM STUDENT S
INNER JOIN ENROL E ON E.STU_NO = S.STU_NO 
INNER JOIN SUBJECT SUB ON E.SUB_NO = SUB.SUB_NO;

SELECT * FROM EMP;
SELECT * FROM SALGRADE;

SELECT EMPNO, ENAME,GRADE
FROM EMP E
INNER JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL;


SELECT * FROM EMP;

SELECT E1.ENAME, E2.ENAME
FROM EMP E1
INNER JOIN EMP E2 ON E1.MGR = E2.EMPNO
WHERE E1.ENAME = 'ALLEN';


SELECT * FROM DEPARTMENT;

SELECT D1.DNAME
FROM DEPARTMENT D1
INNER JOIN DEPARTMENT D2 ON D1.PART = D2.DEPTNO
INNER JOIN DEPARTMENT D3 ON D2.PART = D3.DEPTNO
WHERE D3.DNAME = '공과대학';











