--오라클에서 조건처리
-- 페이 + 보너스의 합이 300이상인 사람을 구하세요
SELECT PAY , BONUS,PAY+BONUS FROM PROFESSOR;

--NVL
SELECT NAME, BONUS,NVL(BONUS,0) FROM PROFESSOR;

--페이+ 보너스의 합이 300이상인 사람을 구하세요.

SELECT * FROM PROFESSOR;

SELECT *FROM PROFESSOR WHERE PAY + NVL(BONUS,0) >=300;
SELECT NVL2(BONUS , 1000, 0) FROM PROFESSOR;

SELECT * FROM STU;


--DECODE(컬럼명 , '값' ,'조건값이랑 동일할떄 출력할 값,'조건만족안했을때 들어갈 값 ');

SELECT ENAME , DECODE(JOB,'MANAGER' , '매니저','그외') FROM EMP;
SELECT NAME, DECODE ( SUBSTR(JUMIN,7,1),1,'남자','여자' )FROM STU;
SELECT NAME, SUBSTR(JUMIN,7,1) FROM STU;

SELECT NAME, DECODE ( SUBSTR(JUMIN,7,1),1 ,'남자',3,'남자', '여자' )FROM STU;

SELECT ENAME,JOB,DECODE(JOB ,'MANAGER','매니저','SALESMAN','세일즈맨','그외') AS 직업 FROM EMP;

SELECT * FROM PROFESSOR WHERE BONUS IS NOT NULL;

--서브쿼리(쿼리 안에 또다른 쿼리)
SELECT MAX(STU_HEIGHT) FROM STUDENT;

SELECT *  FROM STUDENT  WHERE STU_HEIGHT = (SELECT MAX(STU_HEIGHT) FROM STUDENT);

--학생들의 전체 평균 키보다 큰키를 가진 학생 출력

SELECT * FROM STUDENT WHERE STU_HEIGHT >= (SELECT AVG(STU_HEIGHT) FROM STUDENT);
SELECT * FROM PROFESSOR;
SELECT * FROM STU;

SELECT * FROM PROFESSOR WHERE TO_CHAR(HIREDATE,'YY')=81 ;

SELECT AVG(HEIGHT) FROM STU WHERE SUBSTR(STUNO,0,2)=94 OR SUBSTR(STUNO,0,2) =95;

SELECT LPAD (SUBSTR(EMAIL,INSTR(EMAIL,'@'),LENGTH(EMAIL)),LENGTH(EMAIL),'*')FROM PROFESSOR;


SELECT  COUNT(
DECODE ( SUBSTR(JUMIN,7,1),1 ,'남자',NULL)) 남자,
COUNT(
DECODE ( SUBSTR(JUMIN,7,1),2, '여자',NULL ))여자 FROM STU ;







