INSERT INTO BOARD VALUES (1,'첫번째게시글','내용111','TEST');
ROLLBACK;

CREATE SEQUENCE TEST_SEQ
INCREMENT BY 1
START WITH 1;
--MINVALUE 1
--MAXVALUE 99999
--NOCYCLE;

DROP SEQUENCE BOARD_SEQ;


SELECT TEST_SEQ.NEXTVAL
FROM DUAL;


INSERT INTO BOARD VALUES (BOARD_SEQ.NEXTVAL,'세번째게시글','내용132','TEST');

CREATE SEQUENCE B_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE TABLE TBL_BOARD (
    BOARDNO     NUMBER PRIMARY KEY ,  -- 게시글번호, 시퀀스 사용
    TITLE       VARCHAR2(50) NOT NULL,  -- 제목
    CONTENTS    VARCHAR2(300) NOT NULL,  -- 내용
    USERID      VARCHAR2(20) NOT NULL,  -- 작성자 아이디
    CNT         NUMBER DEFAULT 0,  -- 조회수
    FAVORITE    NUMBER DEFAULT 0,  -- 좋아요수
    KIND        NUMBER NOT NULL,  -- 게시글종류
    CDATETIME   DATE DEFAULT SYSDATE,  -- 작성일
    UDATETIME   DATE DEFAULT SYSDATE  -- 수정일
);

CREATE TABLE TBL_USER (
    USERID       VARCHAR2(20) PRIMARY KEY,   -- 아이디 (PK)
    PASSWORD     VARCHAR2(20) NOT NULL,      -- 비밀번호
    NAME         VARCHAR2(20) NOT NULL,      -- 이름
    BIRTH        CHAR(8) NOT NULL,           -- 생년월일 (6 or 8 → 일반적으로 8자리 사용: YYYYMMDD)
    NICKNAME     VARCHAR2(20) NOT NULL,      -- 닉네임
    PROFILE_IMG  VARCHAR2(20) NOT NULL,      -- 이미지경로
    ADDRESS      VARCHAR2(20) NOT NULL,      -- 주소
    PHONE        VARCHAR2(20) NOT NULL,      -- 핸드폰
    EMAIL        VARCHAR2(20) NOT NULL,      -- 이메일
    GENDER       CHAR(1) NOT NULL,           -- 성별 (M/F)
    STATUS       CHAR(1) NOT NULL,           -- 권한 (A/S/C)
    CDATETIME    DATE DEFAULT SYSDATE NOT NULL,  -- 가입일자
    UDATETIME    DATE DEFAULT SYSDATE NOT NULL   -- 수정일자
);

CREATE TABLE TBL_COMMENT (
    COMMENTNO     NUMBER PRIMARY KEY,         -- 댓글번호 (시퀀스 사용 예정)
    BOARDNO       NUMBER NOT NULL,            -- 게시글번호 (FK)
    CONTENTS      VARCHAR2(300) NOT NULL,     -- 댓글 내용
    USERID        VARCHAR2(20) NOT NULL,      -- 아이디 (FK)
    FAVORITE      NUMBER DEFAULT 0 NOT NULL,  -- 좋아요수
    P_COMMENTNO   NUMBER,                     -- 부모 댓글 번호 (nullable FK)
    CDATETIME     DATE DEFAULT SYSDATE NOT NULL,  -- 작성일
    UDATETIME     DATE DEFAULT SYSDATE NOT NULL   -- 수정일
);


CREATE SEQUENCE COMMENT_SEQ
START WITH 1
INCREMENT BY 1;
-- 1~10: 일반 댓글
INSERT INTO TBL_COMMENT (COMMENTNO, BOARDNO, CONTENTS, USERID, FAVORITE, P_COMMENTNO, CDATETIME, UDATETIME)
VALUES (COMMENT_SEQ.NEXTVAL, 3, '김치찌개에 두부 많이 넣는 거 좋아요!', 'user02', 2, NULL, SYSDATE, SYSDATE);

INSERT INTO TBL_COMMENT (COMMENTNO, BOARDNO, CONTENTS, USERID, FAVORITE, P_COMMENTNO, CDATETIME, UDATETIME)
VALUES (COMMENT_SEQ.NEXTVAL, 4, '배송은 보통 2~3일 걸립니다.', 'admin01', 1, NULL, SYSDATE, SYSDATE);

INSERT INTO TBL_COMMENT (COMMENTNO, BOARDNO, CONTENTS, USERID, FAVORITE, P_COMMENTNO, CDATETIME, UDATETIME)
VALUES (COMMENT_SEQ.NEXTVAL, 5, '이벤트 너무 재밌어요~!', 'user03', 3, NULL, SYSDATE, SYSDATE);

INSERT INTO TBL_COMMENT (COMMENTNO, BOARDNO, CONTENTS, USERID, FAVORITE, P_COMMENTNO, CDATETIME, UDATETIME)
VALUES (COMMENT_SEQ.NEXTVAL, 6, '비오는 날엔 전이 최고죠!', 'user01', 2, NULL, SYSDATE, SYSDATE);

INSERT INTO TBL_COMMENT (COMMENTNO, BOARDNO, CONTENTS, USERID, FAVORITE, P_COMMENTNO, CDATETIME, UDATETIME)
VALUES (COMMENT_SEQ.NEXTVAL, 7, '재입고 일정은 내일 공지 예정입니다.', 'seller01', 1, NULL, SYSDATE, SYSDATE);

INSERT INTO TBL_COMMENT (COMMENTNO, BOARDNO, CONTENTS, USERID, FAVORITE, P_COMMENTNO, CDATETIME, UDATETIME)
VALUES (COMMENT_SEQ.NEXTVAL, 8, '디자인이 깔끔해서 좋아요!', 'user02', 4, NULL, SYSDATE, SYSDATE);

INSERT INTO TBL_COMMENT (COMMENTNO, BOARDNO, CONTENTS, USERID, FAVORITE, P_COMMENTNO, CDATETIME, UDATETIME)
VALUES (COMMENT_SEQ.NEXTVAL, 9, '정말 친절하셔서 감동했어요.', 'user03', 5, NULL, SYSDATE, SYSDATE);

INSERT INTO TBL_COMMENT (COMMENTNO, BOARDNO, CONTENTS, USERID, FAVORITE, P_COMMENTNO, CDATETIME, UDATETIME)
VALUES (COMMENT_SEQ.NEXTVAL, 10, '여기 글 보기 좋아요~', 'user01', 0, NULL, SYSDATE, SYSDATE);

INSERT INTO TBL_COMMENT (COMMENTNO, BOARDNO, CONTENTS, USERID, FAVORITE, P_COMMENTNO, CDATETIME, UDATETIME)
VALUES (COMMENT_SEQ.NEXTVAL, 3, '오늘 저녁도 김치찌개 각입니다.', 'user03', 2, NULL, SYSDATE, SYSDATE);

INSERT INTO TBL_COMMENT (COMMENTNO, BOARDNO, CONTENTS, USERID, FAVORITE, P_COMMENTNO, CDATETIME, UDATETIME)
VALUES (COMMENT_SEQ.NEXTVAL, 5, '이벤트 상품 언제 보내주시나요?', 'user01', 1, NULL, SYSDATE, SYSDATE);

-- 11~20: 대댓글 (P_COMMENTNO 참조)
INSERT INTO TBL_COMMENT (COMMENTNO, BOARDNO, CONTENTS, USERID, FAVORITE, P_COMMENTNO, CDATETIME, UDATETIME)
VALUES (COMMENT_SEQ.NEXTVAL, 3, '두부는 꼭 들어가야죠!', 'user01', 1, 1, SYSDATE, SYSDATE);

INSERT INTO TBL_COMMENT (COMMENTNO, BOARDNO, CONTENTS, USERID, FAVORITE, P_COMMENTNO, CDATETIME, UDATETIME)
VALUES (COMMENT_SEQ.NEXTVAL, 4, '감사합니다~ 기다려볼게요!', 'user02', 0, 2, SYSDATE, SYSDATE);

INSERT INTO TBL_COMMENT (COMMENTNO, BOARDNO, CONTENTS, USERID, FAVORITE, P_COMMENTNO, CDATETIME, UDATETIME)
VALUES (COMMENT_SEQ.NEXTVAL, 5, '당첨되셨나요? 축하드려요!', 'user02', 2, 3, SYSDATE, SYSDATE);

INSERT INTO TBL_COMMENT (COMMENTNO, BOARDNO, CONTENTS, USERID, FAVORITE, P_COMMENTNO, CDATETIME, UDATETIME)
VALUES (COMMENT_SEQ.NEXTVAL, 6, '막걸리 한잔 곁들이면 최고죠 ㅎㅎ', 'user03', 1, 4, SYSDATE, SYSDATE);

INSERT INTO TBL_COMMENT (COMMENTNO, BOARDNO, CONTENTS, USERID, FAVORITE, P_COMMENTNO, CDATETIME, UDATETIME)
VALUES (COMMENT_SEQ.NEXTVAL, 7, '네 감사합니다. 기다릴게요~', 'user03', 1, 5, SYSDATE, SYSDATE);

INSERT INTO TBL_COMMENT (COMMENTNO, BOARDNO, CONTENTS, USERID, FAVORITE, P_COMMENTNO, CDATETIME, UDATETIME)
VALUES (COMMENT_SEQ.NEXTVAL, 8, '저도 그렇게 생각해요!', 'user01', 2, 6, SYSDATE, SYSDATE);

INSERT INTO TBL_COMMENT (COMMENTNO, BOARDNO, CONTENTS, USERID, FAVORITE, P_COMMENTNO, CDATETIME, UDATETIME)
VALUES (COMMENT_SEQ.NEXTVAL, 9, '정말 감사한 후기네요!', 'admin01', 1, 7, SYSDATE, SYSDATE);

INSERT INTO TBL_COMMENT (COMMENTNO, BOARDNO, CONTENTS, USERID, FAVORITE, P_COMMENTNO, CDATETIME, UDATETIME)
VALUES (COMMENT_SEQ.NEXTVAL, 10, '다음 글도 기대됩니다!', 'user02', 0, 8, SYSDATE, SYSDATE);

INSERT INTO TBL_COMMENT (COMMENTNO, BOARDNO, CONTENTS, USERID, FAVORITE, P_COMMENTNO, CDATETIME, UDATETIME)
VALUES (COMMENT_SEQ.NEXTVAL, 3, '김치찌개엔 계란말이도 필수죠!', 'user02', 1, 9, SYSDATE, SYSDATE);

INSERT INTO TBL_COMMENT (COMMENTNO, BOARDNO, CONTENTS, USERID, FAVORITE, P_COMMENTNO, CDATETIME, UDATETIME)
VALUES (COMMENT_SEQ.NEXTVAL, 5, '상품은 다음 주에 배송된다고 들었어요.', 'seller01', 2, 10, SYSDATE, SYSDATE);

COMMIT;