-- 1~10: 일반 댓글
INSERT INTO TBL_COMMENT (COMMENTNO, BOARDNO, CONTENTS, USERID, FAVORITE, P_COMMENTNO, CDATETIME, UDATETIME)
VALUES (COMMENT_SEQ.NEXTVAL, 3, '김치찌개에 두부 많이 넣는 거 좋아요!', 'user02', 2, NULL, SYSDATE, SYSDATE);

INSERT INTO TBL_COMMENT (COMMENTNO, BOARDNO, CONTENTS, USERID, FAVORITE, P_COMMENTNO, CDATETIME, UDATETIME)
VALUES (COMMENT_SEQ.NEXTVAL, 4, '배송은 보통 2~3일 걸립니다.', 'admin01', 1, NULL, SYSDATE, SYSDATE);

INSERT INTO TBL_COMMENT (COMMENTNO, BOARDNO, CONTENTS, USERID, FAVORITE, P_COMMENTNO, CDATETIME, UDATETIME)
VALUES (COMMENT_SEQ.NEXTVAL, 5, '이벤트 너무 재밌어요~!', 'user03', 3, NULL, SYSDATE, SYSDATE);

INSERT INTO TBL_COMMENT (COMMENTNO, BOARDNO, CONTENTS, USERID, FAVORITE, P_COMMENTNO, CDATETIME, UDATETIME)
VALUES (COMMENT_SEQ.NEXTVAL, 6, '비오는 날엔 전이 최고죠!', 'user01', 2, NULL, SYSDATE, SYSDATE);

INSERT INTO TBL_COMMENT (COMMENTNO, BOARDNO, CONTENTS, USERID, FAVORITE, P_COMMENTNO, CDATETIME, UDATETIME)
VALUES (COMMENT_SEQ.NEXTVAL, 7, '재입고 일정은 내일 공지 예정입니다.', 'seller01', 1, NULL, SYSDATE, SYSDATE);

INSERT INTO TBL_COMMENT (COMMENTNO, BOARDNO, CONTENTS, USERID, FAVORITE, P_COMMENTNO, CDATETIME, UDATETIME)
VALUES (COMMENT_SEQ.NEXTVAL, 8, '디자인이 깔끔해서 좋아요!', 'user02', 4, NULL, SYSDATE, SYSDATE);

INSERT INTO TBL_COMMENT (COMMENTNO, BOARDNO, CONTENTS, USERID, FAVORITE, P_COMMENTNO, CDATETIME, UDATETIME)
VALUES (COMMENT_SEQ.NEXTVAL, 9, '정말 친절하셔서 감동했어요.', 'user03', 5, NULL, SYSDATE, SYSDATE);

INSERT INTO TBL_COMMENT (COMMENTNO, BOARDNO, CONTENTS, USERID, FAVORITE, P_COMMENTNO, CDATETIME, UDATETIME)
VALUES (COMMENT_SEQ.NEXTVAL, 10, '여기 글 보기 좋아요~', 'user01', 0, NULL, SYSDATE, SYSDATE);

INSERT INTO TBL_COMMENT (COMMENTNO, BOARDNO, CONTENTS, USERID, FAVORITE, P_COMMENTNO, CDATETIME, UDATETIME)
VALUES (COMMENT_SEQ.NEXTVAL, 3, '오늘 저녁도 김치찌개 각입니다.', 'user03', 2, NULL, SYSDATE, SYSDATE);

INSERT INTO TBL_COMMENT (COMMENTNO, BOARDNO, CONTENTS, USERID, FAVORITE, P_COMMENTNO, CDATETIME, UDATETIME)
VALUES (COMMENT_SEQ.NEXTVAL, 5, '이벤트 상품 언제 보내주시나요?', 'user01', 1, NULL, SYSDATE, SYSDATE);

-- 11~20: 대댓글 (P_COMMENTNO 참조)
INSERT INTO TBL_COMMENT (COMMENTNO, BOARDNO, CONTENTS, USERID, FAVORITE, P_COMMENTNO, CDATETIME, UDATETIME)
VALUES (COMMENT_SEQ.NEXTVAL, 3, '두부는 꼭 들어가야죠!', 'user01', 1, 1, SYSDATE, SYSDATE);

INSERT INTO TBL_COMMENT (COMMENTNO, BOARDNO, CONTENTS, USERID, FAVORITE, P_COMMENTNO, CDATETIME, UDATETIME)
VALUES (COMMENT_SEQ.NEXTVAL, 4, '감사합니다~ 기다려볼게요!', 'user02', 0, 2, SYSDATE, SYSDATE);

INSERT INTO TBL_COMMENT (COMMENTNO, BOARDNO, CONTENTS, USERID, FAVORITE, P_COMMENTNO, CDATETIME, UDATETIME)
VALUES (COMMENT_SEQ.NEXTVAL, 5, '당첨되셨나요? 축하드려요!', 'user02', 2, 3, SYSDATE, SYSDATE);

INSERT INTO TBL_COMMENT (COMMENTNO, BOARDNO, CONTENTS, USERID, FAVORITE, P_COMMENTNO, CDATETIME, UDATETIME)
VALUES (COMMENT_SEQ.NEXTVAL, 6, '막걸리 한잔 곁들이면 최고죠 ㅎㅎ', 'user03', 1, 4, SYSDATE, SYSDATE);

INSERT INTO TBL_COMMENT (COMMENTNO, BOARDNO, CONTENTS, USERID, FAVORITE, P_COMMENTNO, CDATETIME, UDATETIME)
VALUES (COMMENT_SEQ.NEXTVAL, 7, '네 감사합니다. 기다릴게요~', 'user03', 1, 5, SYSDATE, SYSDATE);

INSERT INTO TBL_COMMENT (COMMENTNO, BOARDNO, CONTENTS, USERID, FAVORITE, P_COMMENTNO, CDATETIME, UDATETIME)
VALUES (COMMENT_SEQ.NEXTVAL, 8, '저도 그렇게 생각해요!', 'user01', 2, 6, SYSDATE, SYSDATE);

INSERT INTO TBL_COMMENT (COMMENTNO, BOARDNO, CONTENTS, USERID, FAVORITE, P_COMMENTNO, CDATETIME, UDATETIME)
VALUES (COMMENT_SEQ.NEXTVAL, 9, '정말 감사한 후기네요!', 'admin01', 1, 7, SYSDATE, SYSDATE);

INSERT INTO TBL_COMMENT (COMMENTNO, BOARDNO, CONTENTS, USERID, FAVORITE, P_COMMENTNO, CDATETIME, UDATETIME)
VALUES (COMMENT_SEQ.NEXTVAL, 10, '다음 글도 기대됩니다!', 'user02', 0, 8, SYSDATE, SYSDATE);

INSERT INTO TBL_COMMENT (COMMENTNO, BOARDNO, CONTENTS, USERID, FAVORITE, P_COMMENTNO, CDATETIME, UDATETIME)
VALUES (COMMENT_SEQ.NEXTVAL, 3, '김치찌개엔 계란말이도 필수죠!', 'user02', 1, 9, SYSDATE, SYSDATE);

INSERT INTO TBL_COMMENT (COMMENTNO, BOARDNO, CONTENTS, USERID, FAVORITE, P_COMMENTNO, CDATETIME, UDATETIME)
VALUES (COMMENT_SEQ.NEXTVAL, 5, '상품은 다음 주에 배송된다고 들었어요.', 'seller01', 2, 10, SYSDATE, SYSDATE);

COMMIT;
