SELECT ROWNUM, S.* FROM STUDENT S
WHERE ROWNUM <=5;

SELECT * 
FROM (
SELECT ROWNUM AS RN , S.*
FROM STUDENT S)
WHERE RN BETWEEN 3 AND 6;

SELECT ROWNUM ,S.* FROM STUDENT S
ORDER BY STU_HEIGHT DESC;


--학생테이블에서 키가 큰 상위 5명만 출력

SELECT * FROM STUDENT S
ORDER BY STU_HEIGHT DESC;

SELECT ROWNUM ,S.*
FROM(
SELECT * FROM STUDENT
WHERE STU_HEIGHT IS NOT NULL
ORDER BY STU_HEIGHT DESC) S
WHERE ROWNUM BETWEEN 1 AND 5;

--평균급여가 2번째로 큰 부서의 부서명 ,평균급여 출력

SELECT * 
FROM EMP;

SELECT *
FROM DEPT;

SELECT DNAME,평균급여
FROM(
SELECT ROWNUM RN,E.*
FROM(
SELECT DNAME ,ROUND(AVG(SAL),0) 평균급여
FROM EMP E
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
GROUP BY DNAME
ORDER BY ROUND(AVG(SAL),0) DESC
) E
)
WHERE RN=2
;






