--UNION ,UNION ALL
--SELECT쿼리 실행 결과 합쳐주는 명령어

SELECT 
STU_NO,STU_NAME,STU_DEPT
FROM STUDENT
WHERE STU_HEIGHT >=170
UNION
SELECT 
STU_NO,STU_NAME,STU_DEPT
FROM STUDENT
WHERE STU_WEIGHT >=50;


SELECT 
STU_NO,STU_NAME,STU_DEPT
FROM STUDENT
WHERE STU_HEIGHT >=170
UNION ALL
SELECT 
STU_NO,STU_NAME,STU_DEPT
FROM STUDENT
WHERE STU_WEIGHT >=50;

--주의점
--1.컬럽의개수,타입이 같아야한다.
--2.컬럼의이름(별칭)은 먼저나오는 쿼리의 이름을 따른다.

SELECT STU_NAME FROM STUDENT
UNION
SELECT COUNT(*) FROM STUDENT; //컬럼의 타입이 다르기 떄문에 불가능

SELECT STU_NAME AS TEMP FROM STUDENT --컬럼의 이름은 첫번쨰를 따른다.
UNION
SELECT STU_DEPT FROM STUDENT;

SELECT STU_NAME AS TEMP FROM STUDENT 
UNION
SELECT STU_NAME ,STU_DEPT FROM STUDENT; --컬럼의 개수가 다르므로 불가능


SELECT * FROM STUDENT;

SELECT * FROM ENROL;

SELECT STU_NAME 이름 ,AVG(ENR_GRADE) 평균점수 ,1 AS ORDERKEY
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY STU_NAME
UNION
SELECT '평균점수' ,(SELECT ROUND(AVG(ENR_GRADE),1) FROM ENROL), 2 AS ORDERKEY
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
ORDER BY ORDERKEY ,평균점수 DESC
;

SELECT 이름 ,평균점수 FROM
(SELECT STU_NAME 이름 ,AVG(ENR_GRADE) 평균점수 ,1 AS ORDERKEY
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY STU_NAME
UNION
SELECT '평균점수' ,(SELECT ROUND(AVG(ENR_GRADE),1) FROM ENROL), 2 AS ORDERKEY
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
ORDER BY ORDERKEY ,평균점수 DESC
);


SELECT * FROM EMP;

SELECT * FROM DEPT;

SELECT DNAME 부서명 , ROUND(AVG(SAL),0) 전체평균 ,1 AS ORDERKEY
FROM EMP  E
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
GROUP BY DNAME
UNION
SELECT '전체 평균' ,(SELECT ROUND(AVG(SAL))FROM EMP) ,2 AS ORDERKEY
FROM EMP
ORDER BY ORDERKEY, 전체평균 DESC
;

SELECT 부서명 , 전체평균
FROM
(
SELECT DNAME 부서명 , ROUND(AVG(SAL),0) 전체평균 ,1 AS ORDERKEY
FROM EMP  E
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
GROUP BY DNAME
UNION
SELECT '전체 평균' ,ROUND(AVG(SAL)) ,2 AS ORDERKEY
FROM EMP
ORDER BY ORDERKEY, 전체평균 DESC
);




