SELECT * FROM TBL_USER;
SELECT * FROM tbl_board;
SELECT * FROM TBL_COMMENT;


--각 유저가 작성한 게시글의 수(출력 컬럼 : 유저아이디 , 이름 , 게시글 개수)

SELECT B.USERID , NAME , COUNT(*)
FROM TBL_BOARD B
INNER JOIN TBL_USER U ON B.USERID = U.USERID
GROUP BY B.USERID , NAME 
;

SELECT U.USERID , NAME , COUNT(*)
FROM TBL_USER U
LEFT JOIN TBL_BOARD B ON B.USERID = U.USERID
GROUP BY U.USERID , NAME ;

SELECT U.USERID , NAME , COUNT(*)
FROM TBL_BOARD B
RIGHT JOIN TBL_USER U ON B.USERID = U.USERID
GROUP BY U.USERID , NAME 
;

-- 각유저가 작성한 댓글의수 (출력 컬럼 : 유저 아이디 , 이름 , 댓글개수

SELECT U.USERID , NAME , COUNT(COMMENTNO)
FROM TBL_USER U
LEFT JOIN TBL_COMMENT C ON C.USERID = U.USERID
GROUP BY U.USERID , NAME ;







