-- 1. 학생들의 시험 평균 점수가 가장 높은 학생과 가장 낮은 학생의 차이를 구하시오
-- (STUDENT, ENROL)

SELECT * FROM STUDENT;
SELECT * FROM ENROL;

SELECT MAX(AVG(ENR_GRADE)), MIN(AVG(ENR_GRADE)) , MAX(AVG(ENR_GRADE))-MIN(AVG(ENR_GRADE))
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY STU_NAME;


-- 2. 2개의 수업을 들은 학생들의 평균점수와 1개의 수업을 들은 학생들의 평균점수의 차이를 구하시오.
-- (STUDENT, ENROL)
    SELECT AVG(AVG(ENR_GRADE)) 
    FROM STUDENT S
    INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
    GROUP BY E.STU_NO
    HAVING COUNT(*) =1
    ;

   SELECT  AVG(AVG(ENR_GRADE))
    FROM STUDENT S
    INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
    GROUP BY E.STU_NO
    HAVING COUNT(*) =2
    ;
    
    SELECT (SELECT  AVG(AVG(ENR_GRADE))
    FROM STUDENT S
    INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
    GROUP BY E.STU_NO
    HAVING COUNT(*) =2) - ( SELECT  AVG(AVG(ENR_GRADE))
    FROM STUDENT S
    INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
    GROUP BY E.STU_NO
    HAVING COUNT(*) =1
    )FROM DUAL;
    
    

-- 3. 본인 학과에서 본인보다 몸무게가 큰 학생의 수를 출력하시오. ( 학번, 이름, 학과, 큰 학생 수 출력 )
-- (STUDENT)

SELECT * FROM STUDENT;

SELECT COUNT(S2.STU_DEPT),S1.STU_NO,S1.STU_NAME,S1.STU_DEPT
FROM STUDENT S1
LEFT JOIN  STUDENT S2 ON S1.STU_HEIGHT < S2.STU_HEIGHT AND S1.STU_DEPT = S2.STU_DEPT
GROUP BY S1.STU_NAME ,S1.STU_NO,S1.STU_DEPT
;




-- 4. 공과대학에서 속한 교수들 중 가장 큰 급여를 가지는 사람과 
--	가장 적은 급여를 가지는 사람의 교수 이름, 소속 학과, 직급, 급여를 출력하시오
--	(PROFESSOR, DEPARTMENT)
SELECT * FROM PROFESSOR;
SELECT * FROM DEPARTMENT;

SELECT NAME ,DNAME , POSITION,PAY
FROM PROFESSOR P
    INNER JOIN DEPARTMENT D ON P.DEPTNO = D.DEPTNO
    WHERE PAY =(   
        SELECT MAX(PAY) 
        FROM DEPARTMENT D1 
        INNER JOIN DEPARTMENT D2 ON D1.PART = D2.DEPTNO
        INNER JOIN DEPARTMENT D3 ON D2.PART = D3.DEPTNO
        INNER JOIN PROFESSOR P ON D1.DEPTNO = P.DEPTNO
        WHERE D3.DNAME = '공과대학'
        GROUP BY D3.DEPTNO
) OR PAY=(
    SELECT MIN(PAY) 
    FROM DEPARTMENT D1 
    INNER JOIN DEPARTMENT D2 ON D1.PART = D2.DEPTNO
    INNER JOIN DEPARTMENT D3 ON D2.PART = D3.DEPTNO
    INNER JOIN PROFESSOR P ON D1.DEPTNO = P.DEPTNO
    WHERE D3.DNAME = '공과대학'
    GROUP BY D3.DEPTNO
)
;



SELECT MAX(PAY),MIN(PAY) 
FROM DEPARTMENT D1 
INNER JOIN DEPARTMENT D2 ON D1.PART = D2.DEPTNO
INNER JOIN DEPARTMENT D3 ON D2.PART = D3.DEPTNO
INNER JOIN PROFESSOR P ON D1.DEPTNO = P.DEPTNO
WHERE D3.DNAME = '공과대학'
GROUP BY D3.DEPTNO
;

SELECT *
FROM DEPARTMENT D1 
INNER JOIN DEPARTMENT D2 ON D1.PART = D2.DEPTNO
INNER JOIN DEPARTMENT D3 ON D2.PART = D3.DEPTNO
INNER JOIN PROFESSOR P ON D1.DEPTNO = P.DEPTNO
WHERE D3.DNAME = '공과대학'
;

SELECT MAX(PAY) 
FROM DEPARTMENT D1 
INNER JOIN DEPARTMENT D2 ON D1.PART = D2.DEPTNO
INNER JOIN DEPARTMENT D3 ON D2.PART = D3.DEPTNO
INNER JOIN PROFESSOR P ON D1.DEPTNO = P.DEPTNO
WHERE D3.DNAME = '공과대학'
GROUP BY D3.DEPTNO
;


