SELECT * FROM STUDENT;
SELECT * FROM SUBJECT;

SELECT * FROM STUDENT WHERE STU_grade >= 2 AND STU_GENDER = 'M';
SELECT * FROM STUDENT WHERE STU_DEPT >= '기계' OR STU_GENDER = '전기전자';
--SELECT * FROM STUDENT WHERE STU_DEPT >= '기계' OR STU_DEPT = '전기전자';
SELECT * FROM STUDENT WHERE STU_DEPT IN ('기계', '전기전자');
--SELECT * FROM STUDENT WHERE STU_HEIGHT >= 170 AND STU_HEIGHT <=180;
SELECT * FROM STUDENT WHERE STU_HEIGHT BETWEEN 170 AND 180;
SELECT * FROM STUDENT WHERE STU_NAME LIKE '%옥%';
SELECT * FROM STUDENT WHERE STU_NO LIKE '%3%';

SELECT * FROM STUDENT WHERE STU_WEIGHT >= 50 ORDER BY STU_WEIGHT;

--*STUDENT 테이블 기준*
--1.모든 레코드 출력
--2.STUDENT테이블에서 이름 , 학과 , 학년 출력
--3.컴퓨터 정보과 학생들만 출력
--4.기계과 이면서 남자인 학생들만 출력
--5.몸무게가 50~70이상의 학생들 출력

SELECT * FROM STUDENT;
SELECT STU_NAME , STU_GRADE,STU_DEPT FROM STUDENT;
SELECT * FROM STUDENT WHERE STU_DEPT IN('컴퓨터정보');
SELECT * FROM STUDENT WHERE STU_DEPT = '기계과' OR STU_GENDER = 'M';
SELECT * FROM STUDENT WHERE STU_WEIGHT BETWEEN 50 AND 70;
SELECT * FROM ENROL;