--그룹함수 2
-- SUM , AVG , MAX , MIN , COUNT

SELECT POSITION,SUM(PAY) FROM PROFESSOR GROUP BY POSITION;

SELECT * FROM STU;

SELECT GRADE,AVG(WEIGHT) FROM STU GROUP BY GRADE;

SELECT * FROM PROFESSOR;
SELECT COUNT(BONUS) FROM PROFESSOR; // BONUS가 NULL 이 아닌 레코드의수 

-- STUDENT 테이블에서 각 학과의 학생수

-- STEP3. 각학과에서 남자가 2명이상인 학과명 , 학생수 출력
SELECT  * FROM STUDENT;
SELECT STU_DEPT 
, COUNT(*)FROM STUDENT 
WHERE STU_GENDER='M'
GROUP BY STU_DEPT 
HAVING COUNT(*)>=2;