--EMFNO(사번), EMNAME(직원이름), JOB(직급), MGR(팀장의 사번) , HIREATE(입사일),
-- SAL(급여), COMM(보너스), DEPTNO(부서번호)

SELECT * FROM EMP;
SELECT * FROM salgrade;
SELECT * FROM DEPT;

-- 1번
SELECT LOWER(ENAME) FROM EMP;

--2번
SELECT REPLACE(ENAME ,'SMITH','JOHN') FROM EMP WHERE ENAME = 'SMITH';

--3번
SELECT JOB, LENGTH(JOB) FROM EMP WHERE JOB= 'SALESMAN' ;

--4번
SELECT UPPER(SUBSTR(ENAME,0,1)) || LOWER(SUBSTR(ENAME,2)) FROM EMP;

--5번
SELECT SUBSTR(ENAME , LENGTH(ENAME)-2, LENGTH(ENAME)) FROM EMP;

--6번

SELECT JOB,  COUNT(*) FROM EMP WHERE JOB ='MANAGER' GROUP BY JOB;

--7번

SELECT ENAME ||'('|| JOB ||')'FROM EMP;

-- 8번

SELECT ENAME FROM EMP WHERE ENAME LIKE '%A%' GROUP BY ENAME;

-- 숫자 함수 관련
SELECT * FROM EMP;
--1번
SELECT SUM(SAL) FROM EMP;
SELECT SUM(SUM(SAL)+SUM(SAL)/10)FROM EMP GROUP BY SAL;

--2번

SELECT AVG(SAL) FROM EMP WHERE SAL >=1500 ;

--3번

SELECT DEPTNO,SUM(SAL) FROM EMP GROUP BY DEPTNO;

--4번

SELECT DEPTNO , AVG(SAL) FROM EMP WHERE SAL >= 1300 AND DEPTNO=20 GROUP BY DEPTNO;

--5번

SELECT DEPTNO , MAX(SAL) FROM EMP GROUP BY DEPTNO;

--6번

SELECT ENAME ,SAL FROM EMP ORDER BY SAL DESC;


--날짜함수
SELECT * FROM EMP;
--1번

SELECT ENAME , HIREDATE FROM EMP;

--2번

SELECT ENAME , HIREDATE FROM EMP WHERE HIREDATE >='1981-01-01';

--3번

SELECT ENAME , HIREDATE FROM EMP WHERE HIREDATE <='1981-05-01';

--그룹 함수
SELECT * FROM EMP;

--1번

SELECT DEPTNO ,ROUND( AVG(SAL),2) FROM EMP GROUP BY DEPTNO;

--2번

SELECT DEPTNO , COUNT(*) FROM EMP GROUP BY DEPTNO;

--3번

SELECT DEPTNO , COUNT(*) FROM EMP WHERE SAL >= 1500 GROUP BY DEPTNO HAVING COUNT(*)>=3;








