-- 그룹 함수

SELECT MAX(STU_HEIGHT) AS MAX_HEIGHT FROM STUDENT;
SELECT STU_NAME 이름 FROM STUDENT;
SELECT STU_NAME AS 이름 FROM STUDENT; -- AS 는 생략가능
SELECT AVG(STU_HEIGHT) "평균 키" FROM STUDENT;
SELECT SUM(STU_HEIGHT) 더하기 FROM STUDENT;
SELECT MIN(STU_HEIGHT) 작은키 FROM STUDENT;


SELECT * FROM ENROL;