
SELECT * FROM STUDENT;

UPDATE STUDENT SET STU_HEIGHT = 175 WHERE STU_NAME='박희철';

UPDATE STUDENT SET STU_HEIGHT = STU_HEIGHT +1 , STU_WEIGHT = STU_WEIGHT +1 WHERE STU_DEPT ='기계';
COMMIT;
ROLLBACK;
-- 데이터 변경 ( 수정 및 삭제 , 삽입)
