--OUTER 조인
-- LEFG , RIGHT |LEFT 만 알면 대부분된다.

SELECT * FROM STUDENT S
LEFT JOIN ENROL E ON S.STU_NO = E.STU_NO;

--각 학생들의 시험을 본 개수 출력
-- 이름 개수 출력 .단시험을 하나도 보지 않았으면 개수는 0으로 출력

SELECT S.STU_NO , COUNT(ENR_GRADE),STU_NAME
FROM STUDENT S
LEFT JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY S.STU_NO , STU_NAME; 

SELECT * FROM EMP;

SELECT COUNT(E2.MGR) , E1.ENAME ,E1.EMPNO
FROM EMP E1
LEFT JOIN EMP E2 ON E1.EMPNO = E2.MGR
GROUP BY E1.ENAME ,E1.EMPNO
;

SELECT COUNT(*)
FROM EMP 
GROUP BY MGR ;

-- 학번 ,학생 이름 , 담당교수이름 출력
-- 담당교수가 없으면 담당교수없음 으로 출력
SELECT * 
FROM PROFESSOR;

SELECT *
FROM STU;

SELECT * 
FROM STU S
LEFT JOIN PROFESSOR P ON S.PROFNO = P.PROFNO;

SELECT STU.STUNO ,STU.NAME ,NVL(P1.NAME,'담당교수없음')
FROM STU STU
LEFT JOIN(
SELECT  P.PROFNO ,P.NAME
FROM STU S
LEFT JOIN PROFESSOR P ON S.PROFNO = P.PROFNO
GROUP BY P.PROFNO ,P.NAME
)P1 ON STU.PROFNO = P1.PROFNO
GROUP BY STU.STUNO,STU.NAME ,P1.NAME
;

SELECT  P.PROFNO ,P.NAME
FROM STU S
LEFT JOIN PROFESSOR P ON S.PROFNO = P.PROFNO
GROUP BY P.PROFNO ,P.NAME
;

SELECT S.STU_NO , NVL(TO_CHAR(AVG(ENR_GRADE)),'성적없음') 평균점수
FROM STUDENT S
LEFT JOIN ENROL E ON S.STU_NO =E.STU_NO
GROUP BY S.STU_NO;

--게시판 
-- 번호 제목 글쓴이 날짜 

