-- 날짜함수
--1) SYSDATE - 현재 시간가져오기
--2) TO_CHAR 날짜를 문자포멧으로 TO_DATE -문자를 날짜포멧
SELECT SYSDATE,TO_CHAR(SYSDATE,'YYYY-MM-DD HH:MI:SS') FROM DUAL;

SELECT SYSDATE,TO_CHAR(SYSDATE,'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2025-10-15','YYYY-MM-DD') FROM DUAL;
