-- STUDENT 테이블에서 '컴퓨터정보' 학생들의 편균키는 ?

--PROFESSOR 테이블에서 직급이 '정교수'인 살마들의 급여(PAY) 총합은?

SELECT * FROM STUDENT;
SELECT AVG(STU_HEIGHT) 평균키 FROM STUDENT WHERE STU_DEPT = '기계' ;


SELECT * FROM PROFESSOR;
SELECT SUM(PAY) FROM PROFESSOR  WHERE POSITION = '정교수';