--3. INSERT (테이블에 데이터 삽입)
SELECT * FROM STUDENT;
-- 1. 특정 컬럼에만 데이터를 넣는경우
INSERT INTO STUDENT(STU_NO,STU_NAME,STU_DEPT) VALUES('12341234','홍길동','기계과');
COMMIT;

INSERT INTO STUDENT(STU_NO,STU_NAME,STU_DEPT) VALUES('12341234','김철수','컴퓨터정보');

INSERT INTO STUDENT(STU_NO,STU_NAME,STU_DEPT) VALUES('12341234','홍길동','기계과');
-- 2.모든컬럼에 데이터를 넣는경우


SELECT *FROM STUDENT ; 
DELETE FROM SUDENT;

DELETE FROM STUNDENT WHERE STU_NAME = '홍길동';
DELETE FROM STUNDENT WHERE STU_NAME = '홍길동';

DELETE FROM STUDENT WHERE STU_NAME IN('김철수','홍길동');

ROLLBACK